window.SALT_REPORT = {
  "readyForReview": true,
  "updated": "July 19, 2026",
  "sourceDocUrl": "https://docs.google.com/document/d/11xHUbS85NZxVTeAHOGDcVHmxp6fwzc1aHpkpsqcf8Dk/edit?usp=sharing",
  "followupSourceDocUrl": "https://docs.google.com/document/d/176A894SeWt9TVa-YYt0JAuBB7qtWPnA1CNytS3dX9Ec/edit?usp=sharing",
  "parentTask": "AI-13015",
  "linearBase": "https://linear.app/ai-acrobatics/issue/",
  "reviewers": [
    "Tina",
    "Sidney",
    "Julian"
  ],
  "outcomes": {
    "fixed": {
      "label": "Updated and passed",
      "short": "Fixed",
      "tone": "fixed"
    },
    "passed": {
      "label": "Passed as a user",
      "short": "Passed",
      "tone": "passed"
    },
    "positive": {
      "label": "Working as expected",
      "short": "Working",
      "tone": "positive"
    },
    "protected": {
      "label": "Safely verified",
      "short": "Safely verified",
      "tone": "protected"
    },
    "deferred": {
      "label": "Paused at Tina’s request",
      "short": "Paused",
      "tone": "deferred"
    },
    "open": {
      "label": "Current user proof required",
      "short": "Open",
      "tone": "open"
    },
    "approval": {
      "label": "Release approval required",
      "short": "Approval required",
      "tone": "approval"
    }
  },
  "followups": [
    {
      "id": "R2-01",
      "task": "AI-13135",
      "linearIssue": "AI-13135",
      "section": "Brand guide",
      "title": "Keep words separated in brand guide downloads",
      "issue": "The downloaded brand guide still made some words look joined together, especially in the profile description.",
      "outcome": "fixed",
      "steps": [
        "Opened Brand Studio and clicked its real Export Brand Guide action.",
        "Saved both browser downloads and verified the PDF and genuine JPEG bytes.",
        "Rendered those exact downloaded JPG bytes inside the browser beneath a plain-English full-size review heading."
      ],
      "result": "The genuine PDF and JPG exports share a horizontal canvas, and the actual 1800×852 downloaded JPG is visible at full size for review.",
      "testedAt": "2026-07-19T20:11:31.931Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The downloaded test files were retained privately for verification and were not added to the client report.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-01",
      "beforeImage": "assets/source/image10.png",
      "afterImage": "assets/qa-live/R2-01/after.png",
      "gif": "assets/qa-live/R2-01/preview.gif",
      "video": "assets/qa-live/R2-01/walkthrough.mp4",
      "mediaNote": "The starting download and the readable brand-guide result are shown together below."
    },
    {
      "id": "R2-02",
      "task": "AI-13136",
      "linearIssue": "AI-13136",
      "section": "Content calendar",
      "title": "Give every calendar post a clear subject and useful details",
      "issue": "Calendar entries used broad labels instead of clear subject titles, and some entries did not give enough detail to act on.",
      "outcome": "fixed",
      "steps": [
        "Submitted Tina’s exact one-week calendar request once from the signed-in member screen.",
        "Confirmed the first response returned seven distinct subject titles and seven complete post ideas.",
        "Opened the saved weekly Calendar and confirmed its seven posts, one-week span, and seven days.",
        "Opened one saved day and read its full details."
      ],
      "result": "The weekly request completed on its first submission with seven complete, distinct posts across seven days. The saved Calendar is labeled consistently as a weekly plan, and each day opens with useful details.",
      "testedAt": "2026-07-19T20:27:59.616Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-02",
      "beforeImage": "assets/qa-live/R2-02/before.png",
      "afterImage": "assets/qa-live/R2-02/after.png",
      "gif": "assets/qa-live/R2-02/preview.gif",
      "video": "assets/qa-live/R2-02/walkthrough.mp4",
      "mediaNote": "The original broad entries and the completed seven-day result are shown below. The current iPhone request, saved weekly overview, and day details are linked in Release readiness."
    },
    {
      "id": "R2-03",
      "task": "AI-13137",
      "linearIssue": "AI-13137",
      "section": "SaltBot conversation",
      "title": "Make listing requests finish instead of failing immediately",
      "issue": "Three listing requests, including one with a property link, failed immediately instead of returning a useful script or plan.",
      "outcome": "fixed",
      "steps": [
        "Entered each of Tina’s three Park City listing-script requests.",
        "Waited for every request to complete through the signed-in member chat.",
        "Opened and read each full script, including its opening, property details, and call to action."
      ],
      "result": "All three listing requests now return complete scripts instead of failing immediately.",
      "testedAt": "2026-07-18T03:09:08.838Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-03",
      "beforeImage": "assets/source/image5.png",
      "afterImage": "assets/qa-live/R2-03/after.png",
      "gif": "assets/qa-live/R2-03/preview.gif",
      "video": "assets/qa-live/R2-03/walkthrough.mp4",
      "mediaNote": "Tina’s three original failed requests and the completed member results are shown together below."
    },
    {
      "id": "R2-04",
      "task": "AI-13138",
      "linearIssue": "AI-13138",
      "section": "Content calendar",
      "title": "Create the requested mix without repeated calendar ideas",
      "issue": "The 30-day calendar repeated ideas, returned the wrong number of post types, and included concepts that did not fit the request.",
      "outcome": "fixed",
      "steps": [
        "Created Tina’s 30-day, two-posts-per-week calendar and counted all eight posts.",
        "Asked for new ideas and confirmed none of the eight subject titles repeated.",
        "Requested exactly three Reels and confirmed the revised calendar kept 30 days, eight total posts, and three Reels."
      ],
      "result": "The calendar keeps the requested 30-day cadence and post count through revisions while returning distinct, usable ideas.",
      "testedAt": "2026-07-19T20:26:26.749Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-04",
      "beforeImage": "assets/qa-live/R2-04/before.png",
      "afterImage": "assets/qa-live/R2-04/after.png",
      "gif": "assets/qa-live/R2-04/preview.gif",
      "video": "assets/qa-live/R2-04/walkthrough.mp4",
      "mediaNote": "The repeated starting ideas and the completed 30-day mix with eight distinct posts and three Reels are shown together below."
    },
    {
      "id": "R2-05",
      "task": "AI-13139",
      "linearIssue": "AI-13139",
      "section": "Usage limits",
      "title": "Stop unrelated requests from sharing one limit",
      "issue": "Normal SaltBot use could make a different tool report that its own allowance had already been used.",
      "outcome": "fixed",
      "steps": [
        "Used normal chat after the other calendar and listing checks in this same test window.",
        "Submitted a new member request and waited for it to finish.",
        "Read the completed caption and confirmed no false shared rate-limit message appeared."
      ],
      "result": "Normal chat remains available after ordinary use and no longer shares the specialist-tool allowance.",
      "testedAt": "2026-07-18T03:09:48.125Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-05",
      "beforeImage": "assets/source/image5.png",
      "afterImage": "assets/qa-live/R2-05/after.png",
      "gif": "assets/qa-live/R2-05/preview.gif",
      "video": "assets/qa-live/R2-05/walkthrough.mp4",
      "mediaNote": "The false shared-limit experience and the available completed request are visible side by side."
    },
    {
      "id": "R2-06",
      "task": "AI-13140",
      "linearIssue": "AI-13140",
      "section": "Instagram connection",
      "title": "Connect a different Instagram account without breaking Salt",
      "issue": "A different Instagram account failed to connect, while the original Salt Cinema account could reconnect.",
      "outcome": "protected",
      "steps": [
        "Opened the Instagram connection card using the private review account.",
        "Confirmed the unsupported extra-account action is gone and the supported one-account guidance is visible.",
        "Left @julianbradleytv connected and made no change to any live Instagram connection."
      ],
      "result": "SaltBot clearly explains that a workspace supports one connected Instagram account and that the current account must be disconnected before a different one can be connected. The visible @julianbradleytv account is a private review account, not Salt Cinema’s live Instagram account.",
      "testedAt": "2026-07-19T19:59:08.569Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "No Instagram account was disconnected, replaced, or newly connected during this check.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-06",
      "beforeImage": "assets/source/image7.png",
      "afterImage": "assets/qa-live/R2-06/after.png",
      "gif": "assets/qa-live/R2-06/preview.gif",
      "video": "assets/qa-live/R2-06/walkthrough.mp4",
      "mediaNote": "Tina’s reported failure is shown beside the corrected one-account guidance on the private review account."
    },
    {
      "id": "R2-07",
      "task": "AI-13141",
      "linearIssue": "AI-13141",
      "section": "Facebook connection",
      "title": "Complete the Facebook Pages connection",
      "issue": "Facebook Pages could not be connected from Tina’s account.",
      "outcome": "protected",
      "steps": [
        "Opened Integrations and reviewed the Facebook Pages section.",
        "Confirmed the page gives a clear approval explanation instead of starting an unavailable connection.",
        "Made no change to any Facebook Page or live social permission."
      ],
      "result": "Members now receive a clear explanation when Facebook has not yet approved the live connection path, instead of being sent into a dead end.",
      "testedAt": "2026-07-19T19:59:15.178Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Facebook’s external review still has to be completed before a regular client Page can be connected. No Facebook Page or permission was changed during this check.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-07",
      "beforeImage": "assets/source/image2.png",
      "afterImage": "assets/qa-live/R2-07/after.png",
      "gif": "assets/qa-live/R2-07/preview.gif",
      "video": "assets/qa-live/R2-07/walkthrough.mp4",
      "mediaNote": "The current page and its clear live-account boundary are shown in the recording."
    },
    {
      "id": "R2-08",
      "task": "AI-13142",
      "linearIssue": "AI-13142",
      "section": "Scheduler",
      "title": "Turn on scheduled publishing only after release approval",
      "issue": "A scheduled post reached its chosen time but did not publish automatically.",
      "outcome": "approval",
      "steps": [
        "Scheduled one due post through the same form a member uses, using a private review destination.",
        "Ran the scheduling process for that private post only.",
        "Reopened the queue and confirmed SaltBot completed its internal Published step."
      ],
      "result": "SaltBot completed the private scheduling journey and displayed the finished queue state. Nothing was sent to Instagram or a client account.",
      "testedAt": "2026-07-19T19:46:33.317Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Automatic publishing to Salt’s real Instagram destination remains off until Tina approves the release and the destination can be verified safely.",
      "cleanup": "The private review post and uploaded media were removed after the visual record was captured.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-08",
      "beforeImage": "assets/source/image11.png",
      "afterImage": "assets/qa-live/R2-08/after.png",
      "gif": "assets/qa-live/R2-08/preview.gif",
      "video": "assets/qa-live/R2-08/walkthrough.mp4",
      "mediaNote": "The private due-post result is real. It does not claim that production automatic publishing has been turned on."
    },
    {
      "id": "R2-09",
      "task": "AI-13143",
      "linearIssue": "AI-13143",
      "section": "Scheduler",
      "title": "Show the whole image and caption in the queue",
      "issue": "The queue cropped the media and hid the useful post preview behind a technical-looking link.",
      "outcome": "fixed",
      "steps": [
        "Scheduled one future item through the member form.",
        "Opened its queue card.",
        "Reviewed the uploaded image and caption together."
      ],
      "result": "The queue now shows the planned image and readable caption together instead of exposing a long technical link.",
      "testedAt": "2026-07-19T19:46:43.184Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "The queue item stayed inside the private review destination and was not sent to Instagram.",
      "cleanup": "The private review queue item and uploaded media were removed after the visual record was captured.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-09",
      "beforeImage": "assets/source/image11.png",
      "afterImage": "assets/qa-live/R2-09/after.png",
      "gif": "assets/qa-live/R2-09/preview.gif",
      "video": "assets/qa-live/R2-09/walkthrough.mp4",
      "mediaNote": "The old link-heavy queue and the full visual queue card are shown at readable size."
    },
    {
      "id": "R2-10",
      "task": "AI-13144",
      "linearIssue": "AI-13144",
      "section": "DM Inbox",
      "title": "Make DM conversations clear and replies dependable",
      "issue": "It was unclear how to open a conversation, who sent the message, and whether a reply could be sent from the inbox.",
      "outcome": "protected",
      "steps": [
        "Opened one private review conversation and confirmed the sender and receiving inbox were both clear.",
        "Wrote one reply and submitted it once from inside the conversation.",
        "Confirmed the reply appeared as the outgoing message and the reply box cleared."
      ],
      "result": "The complete in-page reply experience worked inside the private review conversation, including sender identity, one saved outgoing reply, and a cleared reply box.",
      "testedAt": "2026-07-18T21:31:41.557Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Nothing was delivered to Instagram and no client or real Instagram member was contacted.",
      "cleanup": "The private review conversation disappeared when the session closed; no client conversation was created.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-10",
      "beforeImage": "assets/qa-live/DMI-03/before.png",
      "afterImage": "assets/qa-live/R2-10/after.png",
      "gif": "assets/qa-live/R2-10/preview.gif",
      "video": "assets/qa-live/R2-10/walkthrough.mp4",
      "mediaNote": "The private conversation, sender identity, single saved reply, and cleared reply box are shown in one member journey."
    },
    {
      "id": "R2-11",
      "task": "AI-13145",
      "linearIssue": "AI-13145",
      "section": "Instagram Audit",
      "title": "Keep Instagram Audit available after normal SaltBot use",
      "issue": "Instagram Audit showed an allowance message even when its own audit allowance had not been used.",
      "outcome": "fixed",
      "steps": [
        "Submitted a normal SaltBot caption request and waited for that generation to complete.",
        "Continued in the same signed-in browser journey to Instagram Audit.",
        "Submitted the Instagram Audit once and waited for its result to finish on that first attempt.",
        "Confirmed the completed public-account audit normalized the requested handle."
      ],
      "result": "After a normal SaltBot request completed, Instagram Audit remained available, accepted one public-account audit, and completed on the first submission.",
      "testedAt": "2026-07-18T21:26:49.926Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "Only the private review member and public profile information were used. No social connection or client channel was changed.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-11",
      "beforeImage": "assets/source/image4.png",
      "afterImage": "assets/qa-live/R2-11/after.png",
      "gif": "assets/qa-live/R2-11/preview.gif",
      "video": "assets/qa-live/R2-11/walkthrough.mp4",
      "mediaNote": "The signed-in Instagram Audit journey and completed result are shown in the available recording."
    },
    {
      "id": "R2-12",
      "task": "AI-13146",
      "linearIssue": "AI-13146",
      "section": "Carousel Designer",
      "title": "Give carousel slides layout controls and a Canva handoff",
      "issue": "Carousel text could be edited, but alignment, position, size, spacing, and the next step into Canva were unclear.",
      "outcome": "fixed",
      "steps": [
        "Opened Carousel Designer and changed the visible layout controls.",
        "Confirmed the layout choices remained after reload.",
        "Opened the Canva finishing guidance and reviewed the handoff steps."
      ],
      "result": "Carousel Designer keeps its layout controls and clearly explains the Canva finishing path.",
      "testedAt": "2026-07-18T21:31:57.499Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-12",
      "beforeImage": "assets/qa-live/CAR-04/before.png",
      "afterImage": "assets/qa-live/R2-12/after.png",
      "gif": "assets/qa-live/R2-12/preview.gif",
      "video": "assets/qa-live/R2-12/walkthrough.mp4",
      "mediaNote": "The layout controls are shown directly; the Canva guidance was checked as the next step in the same member journey."
    },
    {
      "id": "R2-13",
      "task": "AI-13147",
      "linearIssue": "AI-13147",
      "section": "AI Self-Clone",
      "title": "Keep Self-Clone available after normal SaltBot use",
      "issue": "Self-Clone showed an allowance message after other SaltBot activity even when Self-Clone itself had not been used.",
      "outcome": "fixed",
      "steps": [
        "Submitted a normal SaltBot caption request and waited for the finished result.",
        "Continued in the same signed-in journey to AI Self-Clone.",
        "Confirmed the Self-Clone form and Generate action remained available without a shared allowance message.",
        "Stopped before choosing a photo, granting likeness consent, or starting an image generation."
      ],
      "result": "After normal SaltBot use, Self-Clone remained available and did not inherit the unrelated conversation allowance.",
      "testedAt": "2026-07-18T21:27:21.754Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "This check confirms allowance independence only. No photo was selected and no Self-Clone image generation was started or claimed.",
      "cleanup": "No Self-Clone image or saved result was created by this allowance check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#followup-R2-13",
      "beforeImage": "assets/qa-live/SELF-01/after.png",
      "afterImage": "assets/qa-live/R2-13/after.png",
      "gif": "assets/qa-live/R2-13/preview.gif",
      "video": "assets/qa-live/R2-13/walkthrough.mp4",
      "mediaNote": "The starting allowance message is shown beside the available Self-Clone form reached after normal SaltBot use. No image generation is claimed."
    }
  ],
  "items": [
    {
      "outcome": "fixed",
      "steps": [
        "Opened a fresh signed-in dashboard.",
        "Checked the welcome area, template row, and main request box together."
      ],
      "result": "The starting screen presents one calm welcome area, one template row, and one main request box.",
      "testedAt": "2026-07-17T01:25:05.003Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DASH-01",
      "beforeImage": "assets/source/image8.png",
      "afterImage": "assets/qa-live/DASH-01/after.png",
      "gif": "assets/qa-live/DASH-01/preview.gif",
      "video": "assets/qa-live/DASH-01/walkthrough.mp4",
      "id": "DASH-01",
      "task": "AI-13021",
      "section": "Dashboard",
      "title": "Make the dashboard calmer and easier to scan",
      "issue": "The dashboard felt busier than the clean starting screens in ChatGPT and Claude.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the dashboard at the desktop client-review size.",
        "Read the complete Workspace sentence and checked its visible line behavior."
      ],
      "result": "The full Workspace sentence stays together on one line at the tested desktop size.",
      "testedAt": "2026-07-17T01:25:11.406Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DASH-02",
      "beforeImage": "assets/source/image8.png",
      "afterImage": "assets/qa-live/DASH-02/after.png",
      "gif": "assets/qa-live/DASH-02/preview.gif",
      "video": "assets/qa-live/DASH-02/walkthrough.mp4",
      "id": "DASH-02",
      "task": "AI-13017",
      "section": "Dashboard",
      "title": "Keep the workspace sentence on one line",
      "issue": "The word “workspace” wrapped onto its own line in the welcome message.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the dashboard.",
        "Checked the single Quick templates section for planning, script, carousel, and listing starters."
      ],
      "result": "Week Plan, Month Plan, Script, Carousel, and listing starters are grouped in one Quick templates area.",
      "testedAt": "2026-07-17T01:25:18.073Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DASH-03",
      "beforeImage": "assets/source/image8.png",
      "afterImage": "assets/qa-live/DASH-03/after.png",
      "gif": "assets/qa-live/DASH-03/preview.gif",
      "video": "assets/qa-live/DASH-03/walkthrough.mp4",
      "id": "DASH-03",
      "task": "AI-13018",
      "section": "Dashboard",
      "title": "Keep every quick template in one section",
      "issue": "Week Plan, Month Plan, Script, and Carousel were separated from the other quick templates even though they serve the same purpose.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Typed a new prompt without sending it.",
        "Saved it deliberately, opened the collapsed Saved prompts area, and reopened the saved request."
      ],
      "result": "The dashboard shows an optional Saved prompts section instead of automatically exposing recent prompts.",
      "testedAt": "2026-07-17T01:39:23.328Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DASH-04",
      "beforeImage": "assets/source/image8.png",
      "afterImage": "assets/qa-live/DASH-04/after.png",
      "gif": "assets/qa-live/DASH-04/preview.gif",
      "video": "assets/qa-live/DASH-04/walkthrough.mp4",
      "id": "DASH-04",
      "task": "AI-13016",
      "section": "Dashboard",
      "title": "Replace Recent Prompts with saved prompts",
      "issue": "The dashboard automatically showed recent prompts. Tina asked for an optional, collapsed place where users can deliberately save and reopen their own prompts.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Restarted onboarding at question 1 and completed all 29 live questions as a member.",
        "Generated the new strategy, reviewed its full details, and downloaded the PDF from the onboarding completion window.",
        "Finished onboarding, opened the same strategy from Profile, downloaded it again, and compared the visible content, page count, page size, branding, and first-page previews."
      ],
      "result": "The onboarding and Profile buttons downloaded the same 5-page polished Salt Cinema strategy format with matching strategy content.",
      "testedAt": "2026-07-17T04:08:42.505Z",
      "revision": "6590830ec5a25e93994b8a5fac47eaa68704ccff",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "Both files remain in the private review folder for verification. The check used only the dedicated review account.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-ONB-01",
      "beforeImage": "assets/qa-live/ONB-01/before.png",
      "afterImage": "assets/qa-live/ONB-01/after.png",
      "gif": "assets/qa-live/ONB-01/preview.gif",
      "video": "assets/qa-live/ONB-01/walkthrough.mp4",
      "id": "ONB-01",
      "task": "AI-13020",
      "section": "Onboarding",
      "title": "Make both strategy downloads match",
      "issue": "The onboarding page downloaded a different file from the polished strategy document available on the Profile page.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened Brand Studio as a member.",
        "Downloaded both guide formats.",
        "Measured the PDF’s first page, then opened the matching JPG and left it visible for review."
      ],
      "result": "The PDF and JPG share the same horizontal brand-guide canvas for a like-for-like visual review.",
      "testedAt": "2026-07-17T01:39:36.400Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The downloaded test files were retained privately for verification and were not added to the client report.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-BRAND-01",
      "beforeImage": "assets/source/image10.png",
      "afterImage": "assets/qa-live/BRAND-01/after.png",
      "gif": "assets/qa-live/BRAND-01/preview.gif",
      "video": "assets/qa-live/BRAND-01/walkthrough.mp4",
      "id": "BRAND-01",
      "task": "AI-13019",
      "section": "Brand Studio",
      "title": "Export the brand guide horizontally",
      "issue": "The PDF used a vertical page even though the matching brand-guide image was horizontal.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Downloaded the PDF and JPG together.",
        "Confirmed the PDF’s first page is horizontal.",
        "Opened the matching JPG on the same horizontal guide canvas and left it visible for review."
      ],
      "result": "The PDF and JPG share the same horizontal brand-guide canvas for a like-for-like visual review.",
      "testedAt": "2026-07-17T01:39:49.820Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The downloaded test files were retained privately for verification and were not added to the client report.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-BRAND-02",
      "beforeImage": "assets/source/image10.png",
      "afterImage": "assets/qa-live/BRAND-02/after.png",
      "gif": "assets/qa-live/BRAND-02/preview.gif",
      "video": "assets/qa-live/BRAND-02/walkthrough.mp4",
      "id": "BRAND-02",
      "task": "AI-13022",
      "section": "Brand Studio",
      "title": "Give the brand guide readable spacing",
      "issue": "Words ran together in the downloaded brand guide, making the profile description difficult to read.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Created a practical Home Staging carousel through the normal member chat.",
        "Ran Platform Checker against visible YouTube and Reddit sources and chose Use refined version.",
        "Opened the full revised carousel, reloaded the page, and reopened that same saved document."
      ],
      "result": "The updated carousel replaces the original in the main conversation immediately, and the same updated document remains after reload.",
      "testedAt": "2026-07-17T03:34:09.525Z",
      "revision": "6590830ec5a25e93994b8a5fac47eaa68704ccff",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-01",
      "beforeImage": "assets/source/image6.png",
      "afterImage": "assets/qa-live/CHAT-01/after.png",
      "gif": "assets/qa-live/CHAT-01/preview.gif",
      "video": "assets/qa-live/CHAT-01/walkthrough.mp4",
      "id": "CHAT-01",
      "task": "AI-13023",
      "section": "Chatting with SaltBot",
      "title": "Apply the Platform Checker revision to the carousel",
      "issue": "Selecting Use refined version did not update the carousel in the main conversation or keep the refined version after reopening the page.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Created the five-slide carousel and read every headline and body line in its full document.",
        "Selected Generate images, then opened the completed carousel instead of relying on the compact chat card.",
        "Confirmed all five finished images loaded and compared every finished slide with the approved copy."
      ],
      "result": "All five carousel images finish inside the full viewer without removing or rewriting any approved slide copy.",
      "testedAt": "2026-07-17T03:03:17.936Z",
      "revision": "58a6d5def59e55e40cadc1a90402b313e923f5fe",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-02",
      "beforeImage": "assets/source/image1.png",
      "afterImage": "assets/qa-live/CHAT-02/after.png",
      "gif": "assets/qa-live/CHAT-02/preview.gif",
      "video": "assets/qa-live/CHAT-02/walkthrough.mp4",
      "id": "CHAT-02",
      "task": "AI-13024",
      "section": "Chatting with SaltBot",
      "title": "Generate images without losing approved carousel copy",
      "issue": "After Tina approved the carousel copy, image generation repeatedly stopped with an error or risked replacing the approved copy during another attempt.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Asked for exactly ten listing hooks with different ideas and structures.",
        "Counted the finished options.",
        "Compared every pair for repeated wording and concepts."
      ],
      "result": "SaltBot returned exactly ten materially different listing hooks.",
      "testedAt": "2026-07-17T02:32:37.825Z",
      "revision": "58a6d5def59e55e40cadc1a90402b313e923f5fe",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-03",
      "beforeImage": "assets/qa-live/CHAT-03/before.png",
      "afterImage": "assets/qa-live/CHAT-03/after.png",
      "gif": "assets/qa-live/CHAT-03/preview.gif",
      "video": "assets/qa-live/CHAT-03/walkthrough.mp4",
      "id": "CHAT-03",
      "task": "AI-13025",
      "section": "Chatting with SaltBot",
      "title": "Create ten genuinely different listing hooks",
      "issue": "A request for ten listing hooks returned near-duplicates made from the same few words instead of ten useful approaches.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Created a complete caption and waited for it to finish.",
        "Started a new carousel in the same conversation.",
        "Checked the original caption both while the new work was running and after it finished."
      ],
      "result": "The earlier finished answer remains visible while a new asset is created and after that work completes.",
      "testedAt": "2026-07-17T02:56:03.705Z",
      "revision": "58a6d5def59e55e40cadc1a90402b313e923f5fe",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-04",
      "beforeImage": "assets/source/image5.png",
      "afterImage": "assets/qa-live/CHAT-04/after.png",
      "gif": "assets/qa-live/CHAT-04/preview.gif",
      "video": "assets/qa-live/CHAT-04/walkthrough.mp4",
      "id": "CHAT-04",
      "task": "AI-13026",
      "section": "Chatting with SaltBot",
      "title": "Keep completed answers visible during the next request",
      "issue": "A completed explanation could disappear when a new asset started or failed, leaving the earlier answer unavailable in the conversation.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Generated a set of hooks through the member chat.",
        "Asked SaltBot to generate the complete script from hook 4.",
        "Reloaded the saved conversation and reread the finished script."
      ],
      "result": "Generate Script returns a complete saved script, and the conversation remains intact after reload.",
      "testedAt": "2026-07-17T02:57:07.391Z",
      "revision": "58a6d5def59e55e40cadc1a90402b313e923f5fe",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-05",
      "beforeImage": "assets/source/image5.png",
      "afterImage": "assets/qa-live/CHAT-05/after.png",
      "gif": "assets/qa-live/CHAT-05/preview.gif",
      "video": "assets/qa-live/CHAT-05/walkthrough.mp4",
      "id": "CHAT-05",
      "task": "AI-13027",
      "section": "Chatting with SaltBot",
      "title": "Return and save a complete script from a hook",
      "issue": "Generate Script could return an empty result or replace the conversation with an empty answer during another attempt.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Used the supplied Just Listed request with the property details.",
        "Waited for the finished answer.",
        "Read the hook, property details, lifestyle, and call to action together."
      ],
      "result": "The Just Listed template returns the complete announcement instead of a hook or blank card.",
      "testedAt": "2026-07-17T02:25:16.888Z",
      "revision": "58a6d5def59e55e40cadc1a90402b313e923f5fe",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-06",
      "beforeImage": "assets/source/image5.png",
      "afterImage": "assets/qa-live/CHAT-06/after.png",
      "gif": "assets/qa-live/CHAT-06/preview.gif",
      "video": "assets/qa-live/CHAT-06/walkthrough.mp4",
      "id": "CHAT-06",
      "task": "AI-13028",
      "section": "Chatting with SaltBot",
      "title": "Return a complete Just Listed announcement",
      "issue": "The supplied Just Listed template sometimes returned only a hook or a blank card instead of the complete announcement.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Requested a structured four-frame Story sequence.",
        "Waited for the finished response.",
        "Read every finished section and confirmed it was clear and usable."
      ],
      "result": "The finished four-frame Story is presented as clear, readable content.",
      "testedAt": "2026-07-17T02:49:03.008Z",
      "revision": "58a6d5def59e55e40cadc1a90402b313e923f5fe",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CHAT-07",
      "beforeImage": "assets/source/image5.png",
      "afterImage": "assets/qa-live/CHAT-07/after.png",
      "gif": "assets/qa-live/CHAT-07/preview.gif",
      "video": "assets/qa-live/CHAT-07/walkthrough.mp4",
      "id": "CHAT-07",
      "task": "AI-13029",
      "section": "Chatting with SaltBot",
      "title": "Show generated answers as readable content",
      "issue": "Some generated answers could appear as technical structured data or an error instead of useful, readable content.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the main navigation.",
        "Read the Discover destinations in their visible order."
      ],
      "result": "Connect Social appears directly under Teleprompter and above Insights.",
      "testedAt": "2026-07-17T01:26:06.480Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SOC-01",
      "beforeImage": "assets/source/image2.png",
      "afterImage": "assets/qa-live/SOC-01/after.png",
      "gif": "assets/qa-live/SOC-01/preview.gif",
      "video": "assets/qa-live/SOC-01/walkthrough.mp4",
      "id": "SOC-01",
      "task": "AI-13030",
      "section": "Connect Social",
      "title": "Place Connect Social above Insights",
      "issue": "Connect Social was difficult to find below Insights. Tina asked for it directly under Teleprompter.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "protected",
      "steps": [
        "Opened Integrations.",
        "Reviewed the Facebook Pages connection and its current approval message without starting or changing a connection."
      ],
      "result": "The Facebook connection now gives members a clear explanation instead of opening a connection that Facebook has not approved yet.",
      "testedAt": "2026-07-18T02:05:16.838Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "No Facebook permission, Page, or live connection was changed. Facebook’s external review remains the only step outside SaltBot.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SOC-02",
      "beforeImage": "assets/source/image2.png",
      "afterImage": "assets/qa-live/SOC-02/after.png",
      "gif": "assets/qa-live/SOC-02/preview.gif",
      "video": "assets/qa-live/SOC-02/walkthrough.mp4",
      "id": "SOC-02",
      "task": "AI-13032",
      "section": "Connect Social",
      "title": "Complete the Facebook Pages connection",
      "issue": "The Facebook Pages connection was not available for Tina to complete.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "protected",
      "steps": [
        "Opened the Instagram connection card as a member.",
        "Checked that the unsupported second-account action is absent.",
        "Read the one-account workspace guidance without changing the live Instagram connection."
      ],
      "result": "The page no longer sends members into an unsupported extra-account flow and clearly explains the supported one-account path. A different live Instagram account was not authorized, so this safely verifies the corrected guidance rather than claiming that a second account connected.",
      "testedAt": "2026-07-17T03:36:24.601Z",
      "revision": "6590830ec5a25e93994b8a5fac47eaa68704ccff",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Connecting a different live Instagram account would change an active social authorization. No Instagram account was disconnected, replaced, or newly authorized during this check.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SOC-03",
      "beforeImage": "assets/source/image7.png",
      "afterImage": "assets/qa-live/SOC-03/after.png",
      "gif": "assets/qa-live/SOC-03/preview.gif",
      "video": "assets/qa-live/SOC-03/walkthrough.mp4",
      "id": "SOC-03",
      "task": "AI-13031",
      "section": "Connect Social",
      "title": "Connect a different Instagram account",
      "issue": "A newly authorized Instagram account ended on a connection-failed screen.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "protected",
      "steps": [
        "Opened the Instagram connection status using the private test account.",
        "Confirmed the integration page loads normally.",
        "Kept @salt_cinema connected and untouched."
      ],
      "result": "The connection page is healthy, and the live Salt Cinema connection was deliberately preserved instead of being disconnected merely for a test.",
      "testedAt": "2026-07-18T02:05:23.892Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Disconnecting and reconnecting would alter Tina’s live Instagram permission. That protected client connection was not changed.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SOC-04",
      "beforeImage": "assets/source/image9.png",
      "afterImage": "assets/qa-live/SOC-04/after.png",
      "gif": "assets/qa-live/SOC-04/preview.gif",
      "video": "assets/qa-live/SOC-04/walkthrough.mp4",
      "id": "SOC-04",
      "task": "AI-13033",
      "section": "Connect Social",
      "title": "Keep the Salt Cinema account connected",
      "issue": "The existing Salt Cinema Instagram connection was reported as the one connection that worked and must remain reliable.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the Instagram connection card.",
        "Checked the connected and unconnected states for the old extra-account action."
      ],
      "result": "The unsupported Connect another account option is absent, and the page explains the one-account workspace limit.",
      "testedAt": "2026-07-17T01:26:32.775Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SOC-05",
      "beforeImage": "assets/source/image9.png",
      "afterImage": "assets/qa-live/SOC-05/after.png",
      "gif": "assets/qa-live/SOC-05/preview.gif",
      "video": "assets/qa-live/SOC-05/walkthrough.mp4",
      "id": "SOC-05",
      "task": "AI-13034",
      "section": "Connect Social",
      "title": "Remove the extra-account option when it is unavailable",
      "issue": "Connect another account suggested that multiple Instagram accounts were supported even though the second connection failed.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "approval",
      "steps": [
        "Created one due post inside a private SaltBot test account.",
        "Ran the private scheduling process without connecting or posting to Instagram.",
        "Reopened the private queue and confirmed SaltBot completed its internal processing step."
      ],
      "result": "SaltBot completed the isolated scheduling step for the private post. Publishing to an approved Instagram account at the chosen time was not performed, so scheduled Instagram publishing is not presented as fixed.",
      "testedAt": "2026-07-18T21:35:05.154Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "A chosen-time Instagram publish could send client content. It remains off until the release is approved and the connected Instagram destination can be verified safely.",
      "cleanup": "The private test post and its uploaded media were removed after the proof image was captured.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-01",
      "beforeImage": "assets/source/image11.png",
      "afterImage": "assets/qa-live/SCHED-01/after.png",
      "gif": "assets/qa-live/SCHED-01/preview.gif",
      "video": "assets/qa-live/SCHED-01/walkthrough.mp4",
      "id": "SCHED-01",
      "task": "AI-13035",
      "section": "Post Scheduler",
      "title": "Automatically publish scheduled feed posts",
      "issue": "A scheduled Instagram post became due but did not publish at the chosen time.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "approval",
      "steps": [
        "Created one due Story inside a private SaltBot test account.",
        "Ran the private scheduling process without connecting or posting to Instagram.",
        "Reopened the private queue and confirmed SaltBot completed its internal processing step."
      ],
      "result": "SaltBot completed the isolated scheduling step for the private Story. Publishing to an approved Instagram account at the chosen time was not performed, so scheduled Instagram publishing is not presented as fixed.",
      "testedAt": "2026-07-18T21:35:27.106Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "A chosen-time Instagram Story could send client content. It remains off until the release is approved and the connected Instagram destination can be verified safely.",
      "cleanup": "The private test Story and its uploaded media were removed after the proof image was captured.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-02",
      "beforeImage": "assets/source/image11.png",
      "afterImage": "assets/qa-live/SCHED-02/after.png",
      "gif": "assets/qa-live/SCHED-02/preview.gif",
      "video": "assets/qa-live/SCHED-02/walkthrough.mp4",
      "id": "SCHED-02",
      "task": "AI-13036",
      "section": "Post Scheduler",
      "title": "Automatically publish scheduled stories",
      "issue": "A scheduled Instagram story did not publish at the chosen time.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "positive",
      "steps": [
        "Scheduled one future item through the member form.",
        "Pressed Publish now on that queue card.",
        "Confirmed the item showed Published."
      ],
      "result": "Publish Now completed successfully in a private SaltBot test environment. Nothing was sent to Instagram or any client account.",
      "testedAt": "2026-07-18T21:35:58.679Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Only a private SaltBot test destination was used. Nothing was sent to Instagram or any client account.",
      "cleanup": "The private test post and its uploaded media were removed after the proof image was captured.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-03",
      "beforeImage": "assets/source/image11.png",
      "afterImage": "assets/qa-live/SCHED-03/after.png",
      "gif": "assets/qa-live/SCHED-03/preview.gif",
      "video": "assets/qa-live/SCHED-03/walkthrough.mp4",
      "id": "SCHED-03",
      "task": "AI-13037",
      "section": "Post Scheduler",
      "title": "Keep Publish Now working",
      "issue": "Publish Now successfully sent the reported post and is included as a working control that must continue to pass.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened Scheduler and chose Carousel.",
        "Selected two image files together.",
        "Checked both ordered file previews without submitting the post."
      ],
      "result": "Carousel scheduling accepts and displays multiple ordered images before submission. The check stopped before any social post, account connection, or direct message was sent.",
      "testedAt": "2026-07-18T21:36:08.078Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "The recording stops before any real social post, account connection, or direct message is sent.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-04",
      "beforeImage": "assets/source/image12.png",
      "afterImage": "assets/qa-live/SCHED-04/after.png",
      "gif": "assets/qa-live/SCHED-04/preview.gif",
      "video": "assets/qa-live/SCHED-04/walkthrough.mp4",
      "id": "SCHED-04",
      "task": "AI-13039",
      "section": "Post Scheduler",
      "title": "Upload every image in a carousel",
      "issue": "Carousel scheduling accepted only one image instead of the full ordered set.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the Scheduler compose form.",
        "Checked every visible field from account selection through media upload."
      ],
      "result": "The unnecessary Media Notes field is gone.",
      "testedAt": "2026-07-18T21:37:44.651Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-05",
      "beforeImage": "assets/source/image12.png",
      "afterImage": "assets/qa-live/SCHED-05/after.png",
      "gif": "assets/qa-live/SCHED-05/preview.gif",
      "video": "assets/qa-live/SCHED-05/walkthrough.mp4",
      "id": "SCHED-05",
      "task": "AI-13038",
      "section": "Post Scheduler",
      "title": "Remove Media Notes from the scheduling form",
      "issue": "The normal scheduling form asked members for internal Media Notes that were not needed to create a post.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the Scheduler compose form.",
        "Reviewed the media section and every visible field."
      ],
      "result": "The technical Public Media URL field is gone; members choose a file directly.",
      "testedAt": "2026-07-18T21:38:10.418Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-06",
      "beforeImage": "assets/source/image12.png",
      "afterImage": "assets/qa-live/SCHED-06/after.png",
      "gif": "assets/qa-live/SCHED-06/preview.gif",
      "video": "assets/qa-live/SCHED-06/walkthrough.mp4",
      "id": "SCHED-06",
      "task": "AI-13040",
      "section": "Post Scheduler",
      "title": "Remove the required Public Media URL field",
      "issue": "The form asked members to enter a technical public media address even after they uploaded or selected the content to schedule.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Scheduled one future item through the member form.",
        "Opened its queue card.",
        "Reviewed the uploaded image and caption together."
      ],
      "result": "The queue shows the planned image and caption together instead of exposing a long link. The planned item stayed in a private SaltBot test environment and was never sent to Instagram.",
      "testedAt": "2026-07-19T19:46:21.983Z",
      "revision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "The planned item remained in a private SaltBot test environment and was never sent to Instagram.",
      "cleanup": "The private test queue item and its uploaded media were removed after the proof image was captured.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SCHED-07",
      "beforeImage": "assets/source/image11.png",
      "afterImage": "assets/qa-live/SCHED-07/after.png",
      "gif": "assets/qa-live/SCHED-07/preview.gif",
      "video": "assets/qa-live/SCHED-07/walkthrough.mp4",
      "id": "SCHED-07",
      "task": "AI-13042",
      "section": "Post Scheduler",
      "title": "Show the planned post inside the queue",
      "issue": "The queue showed long media links and notes instead of the image or video and its caption.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "deferred",
      "steps": [
        "Opened DM Automations only to confirm the feature remains available.",
        "Made no workflow, rule, or connection changes."
      ],
      "result": "The larger DM Automations review remains paused exactly as Tina requested.",
      "testedAt": "2026-07-17T01:26:52.611Z",
      "revision": "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "Tina asked that the larger DM Automations review remain paused.",
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DMA-01",
      "beforeImage": "assets/qa-live/DMA-01/before.png",
      "afterImage": "assets/qa-live/DMA-01/after.png",
      "gif": "assets/qa-live/DMA-01/preview.gif",
      "video": "assets/qa-live/DMA-01/walkthrough.mp4",
      "id": "DMA-01",
      "task": "AI-13041",
      "section": "DM Automations",
      "title": "Keep the DM Automations review paused",
      "issue": "Tina asked for more time before giving final feedback on this larger feature.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened DM Inbox with one isolated test conversation.",
        "Selected the conversation and waited for its saved message to appear."
      ],
      "result": "A recent message now opens into its complete conversation view.",
      "testedAt": "2026-07-18T02:05:43.773Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The isolated conversation existed only for this review and disappeared when the session closed; no client records were created.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DMI-01",
      "beforeImage": "assets/qa-live/DMI-01/before.png",
      "afterImage": "assets/qa-live/DMI-01/after.png",
      "gif": "assets/qa-live/DMI-01/preview.gif",
      "video": "assets/qa-live/DMI-01/walkthrough.mp4",
      "id": "DMI-01",
      "task": "AI-13043",
      "section": "DM Inbox",
      "title": "Open a message conversation",
      "issue": "The inbox listed recent messages but did not let Tina open the conversation.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened one isolated test conversation.",
        "Read the contact name, sender handle, receiving inbox, and message label together."
      ],
      "result": "The conversation clearly identifies who sent the message and which inbox received it.",
      "testedAt": "2026-07-18T02:05:50.773Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The isolated conversation existed only for this review and disappeared when the session closed; no client records were created.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DMI-02",
      "beforeImage": "assets/qa-live/DMI-02/before.png",
      "afterImage": "assets/qa-live/DMI-02/after.png",
      "gif": "assets/qa-live/DMI-02/preview.gif",
      "video": "assets/qa-live/DMI-02/walkthrough.mp4",
      "id": "DMI-02",
      "task": "AI-13044",
      "section": "DM Inbox",
      "title": "Show who sent each message",
      "issue": "The inbox did not make the sender and conversation context clear enough to act on.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "protected",
      "steps": [
        "Opened an isolated test conversation.",
        "Wrote a reply and submitted it once from inside the thread.",
        "Confirmed the reply appeared as the outgoing message in that same conversation."
      ],
      "result": "The in-page reply flow completed against an isolated test conversation; no client was contacted and no Instagram message was delivered.",
      "testedAt": "2026-07-18T03:03:18.570Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "This safely verifies the member reply experience without sending a message through Tina’s live Instagram inbox.",
      "cleanup": "The isolated conversation existed only for this review and disappeared when the session closed; no client records were created.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-DMI-03",
      "beforeImage": "assets/qa-live/DMI-03/before.png",
      "afterImage": "assets/qa-live/DMI-03/after.png",
      "gif": "assets/qa-live/DMI-03/preview.gif",
      "video": "assets/qa-live/DMI-03/walkthrough.mp4",
      "id": "DMI-03",
      "task": "AI-13045",
      "section": "DM Inbox",
      "title": "Reply from the conversation",
      "issue": "There was no way to write and send a reply from the opened inbox conversation.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "positive",
      "steps": [
        "Entered a complete private test listing with address, price, property facts, and standout features.",
        "Generated the launch bundle and waited for every section to finish.",
        "Reviewed the Reel, carousel, caption, story, and DM campaign sections."
      ],
      "result": "Listing Launch still completes the full member workflow and returns the expected launch bundle.",
      "testedAt": "2026-07-18T02:08:10.116Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-LIST-01",
      "beforeImage": "assets/qa-live/LIST-01/before.png",
      "afterImage": "assets/qa-live/LIST-01/after.png",
      "gif": "assets/qa-live/LIST-01/preview.gif",
      "video": "assets/qa-live/LIST-01/walkthrough.mp4",
      "id": "LIST-01",
      "task": "AI-13046",
      "section": "Listing Launch",
      "title": "Keep Listing Launch working as expected",
      "issue": "Tina marked Listing Launch as working well, so the same successful member journey must remain intact.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened Instagram Audit with a connected private test account.",
        "Entered the same comparison request shown in Tina’s screenshot.",
        "Ran the audit and opened the completed comparison details."
      ],
      "result": "The comparison accepts the account entry and returns the side-by-side audit without the reported validation error.",
      "testedAt": "2026-07-18T02:09:07.172Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-IGA-01",
      "beforeImage": "assets/source/image4.png",
      "afterImage": "assets/qa-live/IGA-01/after.png",
      "gif": "assets/qa-live/IGA-01/preview.gif",
      "video": "assets/qa-live/IGA-01/walkthrough.mp4",
      "id": "IGA-01",
      "task": "AI-13047",
      "section": "Instagram Audit",
      "title": "Audit another Instagram account",
      "issue": "Auditing another public account failed whether Tina entered a handle, an @handle, or a full profile link.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the member’s saved Brand Studio typography.",
        "Opened Carousel Designer and waited for both saved fonts to load on its canvas.",
        "Returned to Brand Studio and left the exact saved heading and body fonts visible beside the carousel preview."
      ],
      "result": "The carousel uses the same saved heading and body fonts shown in Brand Studio.",
      "testedAt": "2026-07-17T03:53:09.478Z",
      "revision": "6590830ec5a25e93994b8a5fac47eaa68704ccff",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CAR-01",
      "beforeImage": "assets/qa-live/CAR-01/before.png",
      "afterImage": "assets/qa-live/CAR-01/after.png",
      "gif": "assets/qa-live/CAR-01/preview.gif",
      "video": "assets/qa-live/CAR-01/walkthrough.mp4",
      "id": "CAR-01",
      "task": "AI-13048",
      "section": "Carousel Designer",
      "title": "Use the Brand Studio fonts",
      "issue": "Carousel designs did not use the fonts selected in Brand Studio.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened the member’s saved Brand Studio colors.",
        "Rendered carousel copy and checked its primary, secondary, and accent colors against those saved values.",
        "Returned to Brand Studio and left the exact saved palette visible beside the carousel preview."
      ],
      "result": "The carousel uses the same saved color palette shown in Brand Studio.",
      "testedAt": "2026-07-17T03:53:23.545Z",
      "revision": "6590830ec5a25e93994b8a5fac47eaa68704ccff",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CAR-02",
      "beforeImage": "assets/qa-live/CAR-02/before.png",
      "afterImage": "assets/qa-live/CAR-02/after.png",
      "gif": "assets/qa-live/CAR-02/preview.gif",
      "video": "assets/qa-live/CAR-02/walkthrough.mp4",
      "id": "CAR-02",
      "task": "AI-13049",
      "section": "Carousel Designer",
      "title": "Use the Brand Studio colors",
      "issue": "Carousel designs did not use the color palette saved in Brand Studio.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened a blank carousel and chose a real property photo from the device.",
        "Reloaded the page and confirmed the photo was still attached and visible.",
        "Downloaded slide 1 and verified the finished portrait PNG."
      ],
      "result": "A member can upload a property photo, keep it after reload, and export the finished slide as a usable PNG.",
      "testedAt": "2026-07-17T03:53:34.551Z",
      "revision": "6590830ec5a25e93994b8a5fac47eaa68704ccff",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The temporary property photo was removed from the private test account after the check. The exported PNG was retained privately for verification.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CAR-03",
      "beforeImage": "assets/qa-live/CAR-03/before.png",
      "afterImage": "assets/qa-live/CAR-03/after.png",
      "gif": "assets/qa-live/CAR-03/preview.gif",
      "video": "assets/qa-live/CAR-03/walkthrough.mp4",
      "id": "CAR-03",
      "task": "AI-13050",
      "section": "Carousel Designer",
      "title": "Upload a photo as the background",
      "issue": "The Image Background option did not allow Tina to choose a photo from her device.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Changed the slide’s alignment, vertical position, headline size, body size, and side spacing.",
        "Reloaded the page and reread every saved layout value.",
        "Downloaded slide 1 and verified the finished portrait PNG."
      ],
      "result": "The full slide layout remains in place after reload and exports as a usable PNG.",
      "testedAt": "2026-07-18T02:09:17.480Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The exported PNG was retained privately for verification.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CAR-04",
      "beforeImage": "assets/qa-live/CAR-04/before.png",
      "afterImage": "assets/qa-live/CAR-04/after.png",
      "gif": "assets/qa-live/CAR-04/preview.gif",
      "video": "assets/qa-live/CAR-04/walkthrough.mp4",
      "id": "CAR-04",
      "task": "AI-13051",
      "section": "Carousel Designer",
      "title": "Adjust the slide layout",
      "issue": "Text could be edited, but its alignment, position, size, and spacing could not be changed.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Opened Carousel Designer.",
        "Scrolled from the live preview to the download controls and finishing guidance."
      ],
      "result": "The page clearly explains that members can download the PNGs and finish advanced design work in Canva.",
      "testedAt": "2026-07-18T02:09:24.214Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": null,
      "cleanup": "The private test session was closed after this check.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-CAR-05",
      "beforeImage": "assets/qa-live/CAR-05/before.png",
      "afterImage": "assets/qa-live/CAR-05/after.png",
      "gif": "assets/qa-live/CAR-05/preview.gif",
      "video": "assets/qa-live/CAR-05/walkthrough.mp4",
      "id": "CAR-05",
      "task": "AI-13052",
      "section": "Carousel Designer",
      "title": "Make the Canva finishing step clear",
      "issue": "Tina wanted a clear way to finish advanced design work in Canva after creating the carousel in SaltBot.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Restored the completed image from the first request.",
        "Started a second live request with the same synthetic review portrait.",
        "Captured the actual in-progress screen with the old gallery hidden, then waited for the second request to finish."
      ],
      "result": "The previous gallery disappears while a new image is being created, and a clear Creating a fresh result panel takes its place.",
      "testedAt": "2026-07-18T03:26:06.309Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "The review used a computer-generated portrait that does not depict a real person. No client likeness was uploaded.",
      "cleanup": "Both generated review images and their saved copies were removed from the private test account after capture.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SELF-01",
      "beforeImage": "assets/source/image3.png",
      "afterImage": "assets/qa-live/SELF-01/after.png",
      "gif": "assets/qa-live/SELF-01/preview.gif",
      "video": "assets/qa-live/SELF-01/walkthrough.mp4",
      "id": "SELF-01",
      "task": "AI-13053",
      "section": "AI Self-Clone",
      "title": "Hide the previous result during a new generation",
      "issue": "Starting a new request showed the last set of images again, which made the new request look finished before it was ready.",
      "mediaNote": "The reported issue and completed result are shown together below."
    },
    {
      "outcome": "fixed",
      "steps": [
        "Uploaded the explicitly approved synthetic review portrait.",
        "Started a live request and read the stage, percentage, matching progress bar, and expected timing while it ran.",
        "Waited for that same request to finish and confirmed its saved image appeared."
      ],
      "result": "Members see an honest live stage, percentage, progress bar, and expected timing, followed by the completed new image.",
      "testedAt": "2026-07-18T03:25:44.145Z",
      "revision": "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
      "accountBoundary": "A private SaltBot test account created for this review was used. Tina’s account and connected client channels were not used.",
      "boundary": "The review used a computer-generated portrait that does not depict a real person. No client likeness was uploaded.",
      "cleanup": "The first generated review image was kept only long enough for the paired visibility check. Both review images and their saved copies were then removed.",
      "proofUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html#item-SELF-02",
      "beforeImage": "assets/source/image3.png",
      "afterImage": "assets/qa-live/SELF-02/after.png",
      "gif": "assets/qa-live/SELF-02/preview.gif",
      "video": "assets/qa-live/SELF-02/walkthrough.mp4",
      "id": "SELF-02",
      "task": "AI-13054",
      "section": "AI Self-Clone",
      "title": "Show honest progress while new images are created",
      "issue": "A new result could take one to two minutes without making the remaining wait clear.",
      "mediaNote": "The reported issue and completed result are shown together below."
    }
  ],
  "testedRevision": null,
  "testedRevisions": [
    "fe234dad880be2fc4c71f663ff6ff99c33f1d63f",
    "6590830ec5a25e93994b8a5fac47eaa68704ccff",
    "58a6d5def59e55e40cadc1a90402b313e923f5fe",
    "81344e006f9cd5d0e2ec8f8654e2c44320646deb",
    "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc"
  ],
  "requestedRevision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
  "proofRevision": "a3caaa89d2a8e3207ee996f0447bd44ad5d69c79",
  "proofBaseUrl": "https://julianb233.github.io/saltbot-tina-feedback-20260719/proof/tina-july17/index.html",
  "iosTestedRevision": "ba97fa63d2764df53ee8ad5ad3aa0d87f6b406dc",
  "iosTestedAt": "2026-07-19T20:27:59.616Z",
  "iosAppVersion": "1.3.0",
  "iosBuildNumber": "8",
  "iosEnvironment": "Apple iPhone Simulator",
  "iosCurrentSourceRevision": "36adae641e551262421917896d4f786458043ca8",
  "iosCurrentSourceTestedAt": "2026-07-19T22:06:00.000Z"
};
