window.SALT_REPORT = {
  "updated": "July 16, 2026",
  "sourceDocUrl": "https://docs.google.com/document/d/1afuDKr65ZV-bbs1HiJ_aGoK5eR97wWbg4fKagNWNRak/edit?tab=t.0",
  "linearBase": "https://linear.app/ai-acrobatics/issue/",
  "statuses": {
    "passed": {
      "label": "Passed as a user",
      "short": "Passed",
      "tone": "verified"
    },
    "fixed": {
      "label": "Fixed and then passed as a user",
      "short": "Fixed and passed",
      "tone": "review"
    },
    "blocked": {
      "label": "Tested — consent required",
      "short": "Consent required",
      "tone": "external"
    },
    "failed": {
      "label": "Failed — not publishable",
      "short": "Failed",
      "tone": "testing"
    }
  },
  "items": [
    {
      "id": "01",
      "task": "AI-12974",
      "section": "Onboarding",
      "title": "Restart onboarding and finish the strategy",
      "status": "passed",
      "issue": "Restarting onboarding repeatedly stopped Tina at the reported question 28 error, so she could not finish a new strategy.",
      "steps": [
        "Restarted at question 1, continued through every one of the live wizard’s 29 questions, passed question 28, generated the strategy, and landed back on the dashboard."
      ],
      "result": "The reported question 28 error did not recur; the full 29-question restart and final strategy generation completed.",
      "beforeImage": "assets/source/kix.ag6w42k1aeay.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/onboarding-brand/item-01-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-01.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-01.gif",
      "boundary": null,
      "cleanup": "Used the dedicated test account; no Tina account data was touched."
    },
    {
      "id": "02",
      "task": "AI-12973",
      "section": "Onboarding",
      "title": "Show the newest strategy after an update",
      "status": "fixed",
      "issue": "After Tina updated her strategy, SaltBot kept showing an older version instead of the new active one.",
      "steps": [
        "Read the active strategy, submitted one clear update through the member-facing profile editor, then read the active strategy and Version History again."
      ],
      "result": "SaltBot showed the newly updated strategy as active while keeping the earlier strategy in Version History.",
      "beforeImage": "assets/qa-live/onboarding-brand/item-02-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/onboarding-brand/item-02-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-02.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-02.gif",
      "boundary": null,
      "cleanup": "The update stayed in the dedicated test account as the next onboarding check."
    },
    {
      "id": "03",
      "task": "AI-12975",
      "section": "Onboarding",
      "title": "Keep strategy-update instructions out of final notes",
      "status": "fixed",
      "issue": "A strategy-update instruction unexpectedly appeared in the final onboarding notes.",
      "steps": [
        "First submitted the marked strategy update in item 2, then restarted at question 1, walked all 29 questions again, inspected Final Notes, and generated another strategy."
      ],
      "result": "The marked strategy-update instruction was absent from Final Notes, and strategy generation still completed.",
      "beforeImage": "assets/source/kix.npzxuseoqdak.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/onboarding-brand/item-03-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-03.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-03.gif",
      "boundary": null,
      "cleanup": "The temporary final note remains only in the dedicated test account."
    },
    {
      "id": "04",
      "task": "AI-12976",
      "section": "Onboarding",
      "title": "Download a readable strategy document",
      "status": "passed",
      "issue": "The downloaded strategy was a dense text dump that was difficult to scan or understand.",
      "steps": [
        "Opened the current strategy as a member, clicked Download PDF, saved the file, opened it in a standard PDF viewer, and reviewed its headings, cards, spacing, and page layout."
      ],
      "result": "The download opened as a formatted PDF with clear sections rather than the reported plain-text dump.",
      "beforeImage": "assets/source/kix.ingidt63jf7q.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/onboarding-brand/item-04-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-04.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-04.gif",
      "boundary": null,
      "cleanup": "The downloaded PDF is retained only as visual proof for this report."
    },
    {
      "id": "05",
      "task": "AI-12977",
      "section": "Brand Studio",
      "title": "Remove duplicate Voice and Words questions",
      "status": "fixed",
      "issue": "Brand Studio asked for Voice and Words again even though onboarding had already collected that information.",
      "steps": [
        "Opened Brand Studio, scrolled the full visual-control sequence, and checked the live page for the exact duplicate Voice and Words and Brand voice sections."
      ],
      "result": "The duplicate verbal questions are absent; visual controls move from Colors to Typography to Imagery.",
      "beforeImage": "assets/source/kix.3e5pxr1almah.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/onboarding-brand/item-05-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-05.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-05.gif",
      "boundary": null,
      "cleanup": null
    },
    {
      "id": "06",
      "task": "AI-12978",
      "section": "Brand Studio",
      "title": "Remove the generic-caption exercise",
      "status": "fixed",
      "issue": "The visual brand guide asked users to write a generic caption, which did not belong in this workflow.",
      "steps": [
        "Walked the entire Brand Studio control column and searched the member page for the old generic-caption exercise."
      ],
      "result": "The generic-caption exercise does not appear anywhere in the live Brand Studio workflow.",
      "beforeImage": "assets/source/kix.zgzoebpzp0qw.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/onboarding-brand/item-06-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-06.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-06.gif",
      "boundary": null,
      "cleanup": null
    },
    {
      "id": "07",
      "task": "AI-12979",
      "section": "Brand Studio",
      "title": "Make the PDF and JPG brand guide match",
      "status": "fixed",
      "issue": "The old export said Re-Export and produced a PDF and JPG with different layouts and readability problems.",
      "steps": [
        "Clicked Export Brand Guide, captured both real downloads, opened the PDF and JPG with standard file viewers, and compared their visible guide content side by side."
      ],
      "result": "The button uses the corrected label, both files download, and both contain the same ordered compact guide; the PDF is one Letter page and the JPG is a landscape image.",
      "beforeImage": "assets/qa-live/onboarding-brand/item-07-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/onboarding-brand/item-07-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-07.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-07.gif",
      "boundary": null,
      "cleanup": "The two files are retained as the export proof; no social or external publishing occurred."
    },
    {
      "id": "08",
      "task": "AI-12980",
      "section": "Brand Studio",
      "title": "Allow a custom brand font",
      "status": "fixed",
      "issue": "Members could not upload and apply their own licensed font in Brand Studio.",
      "steps": [
        "Opened Typography, uploaded a temporary test font, waited for the upload confirmation, applied it to headings, and verified the heading choice changed to the uploaded font."
      ],
      "result": "A licensed custom font can be uploaded and applied live in Brand Studio.",
      "beforeImage": "assets/qa-live/onboarding-brand/item-08-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/onboarding-brand/item-08-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-08.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-08.gif",
      "boundary": null,
      "cleanup": "The unsaved font choice was discarded after capture; the uploaded test font remains only in the dedicated test account."
    },
    {
      "id": "09",
      "task": "AI-12981",
      "section": "Brand Studio",
      "title": "Remove the unhelpful contrast panel",
      "status": "fixed",
      "issue": "The old Brand Studio showed a large accessibility contrast panel that Tina did not find useful.",
      "steps": [
        "Searched the full live Brand Studio for the old accessibility contrast heading and rows shown in Tina’s screenshot."
      ],
      "result": "The large accessibility contrast panel from Tina’s screenshot is absent from the live member-facing Brand Studio.",
      "beforeImage": "assets/source/kix.56hpay4n5cj.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/onboarding-brand/item-09-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/onboarding-brand/item-09.mp4",
      "gif": "assets/qa-live/onboarding-brand/item-09.gif",
      "boundary": null,
      "cleanup": null
    },
    {
      "id": "10",
      "task": "AI-12982",
      "section": "Chatting with SaltBot",
      "title": "Hide Discover Generators until ready",
      "status": "fixed",
      "issue": "The home screen showed an unfinished Discover Generators section as if it were ready to use.",
      "steps": [
        "Signed in with the dedicated test account.",
        "Opened a fresh SaltBot home screen.",
        "Checked the full visible page for the old section and confirmed the working quick starts remain."
      ],
      "result": "The unfinished Discover Generators section is gone, while Week Plan, Month Plan, Script, Carousel, and Quick Templates are still available.",
      "beforeImage": "assets/qa-live/chat/10-before-tina-report.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/chat/10-after-live-dashboard.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/10-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/10-user-acceptance.gif",
      "boundary": null,
      "cleanup": "No data was created for this visibility check."
    },
    {
      "id": "11",
      "task": "AI-12983",
      "section": "Chatting with SaltBot",
      "title": "Collapse the duplicate Ideas for You section",
      "status": "fixed",
      "issue": "Ideas for You repeated the same kind of prompts as Quick Templates and made the chat screen feel crowded.",
      "steps": [
        "Loaded a real personalized Ideas for You list on the dedicated test profile.",
        "Collapsed the populated list, reopened it, and checked that every card returned.",
        "Collapsed it again and restored the test profile data."
      ],
      "result": "The populated Ideas for You list collapsed completely, reopened with its personalized card intact, and finished collapsed.",
      "beforeImage": "assets/qa-live/chat/11-before-tina-report.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/chat/11-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/11-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/11-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test profile question was restored to its exact prior value."
    },
    {
      "id": "12",
      "task": "AI-12984",
      "section": "Chatting with SaltBot",
      "title": "Create carousel copy before making images",
      "status": "fixed",
      "issue": "Carousel images were generated before Tina could review and refine the words, wasting time and image-generation cost.",
      "steps": [
        "Generated and opened the complete five-slide copy with no finished images yet.",
        "Used the separate Generate images approval action and opened all five finished slide images.",
        "Hard-reloaded the chat and reopened the same five-image carousel."
      ],
      "result": "The same five reviewed slides stayed unchanged; only after approval did five finished images appear, and all five remained visible after reload.",
      "beforeImage": "assets/qa-live/chat/12-before-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/chat/12-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/12-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/12-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "13",
      "task": "AI-12985",
      "section": "Chatting with SaltBot",
      "title": "Stop returning empty carousel or calendar results",
      "status": "fixed",
      "issue": "SaltBot repeatedly said a carousel or calendar was ready, but the result card was empty.",
      "steps": [
        "Generated two carousels and two calendars in one temporary signed-in chat.",
        "Required a visible, openable result after every request.",
        "Reloaded the chat and checked that all four results remained."
      ],
      "result": "All four generations returned complete result cards and remained after reload.",
      "beforeImage": "assets/qa-live/chat/13-before-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/chat/13-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/13-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/13-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "14",
      "task": "AI-12986",
      "section": "Chatting with SaltBot",
      "title": "Keep Zillow facts and finish research answers",
      "status": "fixed",
      "issue": "SaltBot forgot facts it had already pulled from Tina’s Zillow link, contradicted itself about web access, and stopped completing the request.",
      "steps": [
        "Replayed Tina’s exact Park City address and Zillow link in a new chat.",
        "Asked a follow-up without repeating the facts.",
        "Created and opened a public shared-chat snapshot to verify the retained conversation."
      ],
      "result": "SaltBot retained the listing context through the creative rewrite, and the shared snapshot preserved the same facts and follow-up.",
      "beforeImage": "assets/qa-live/chat/14-before-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/chat/14-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/14-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/14-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "15",
      "task": "AI-12987",
      "section": "Chatting with SaltBot",
      "title": "Remember earlier messages without changing strategy",
      "status": "fixed",
      "issue": "When Tina asked for a script from hooks already in the chat, SaltBot lost the reference, used the wrong point of view, and updated her strategy instead.",
      "steps": [
        "Recorded the test account’s strategy state before the chat.",
        "Provided three hooks, then asked for a full script from hook 2 without repeating it.",
        "Opened the complete script to check the hook and point of view, then compared Strategy again."
      ],
      "result": "SaltBot remembered hook 2, produced a complete listing-agent script, and left the strategy unchanged.",
      "beforeImage": "assets/qa-live/chat/15-before-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/chat/15-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/15-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/15-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "16",
      "task": "AI-12988",
      "section": "Chatting with SaltBot",
      "title": "Generate all eight requested monthly posts",
      "status": "fixed",
      "issue": "Tina asked for two posts per week for four weeks, but SaltBot returned only two posts or an empty calendar.",
      "steps": [
        "Requested exactly two posts per week for four weeks.",
        "Opened the calendar and checked both the post and week totals.",
        "Hard-reloaded the chat, reopened the calendar, and checked both totals again."
      ],
      "result": "The calendar contained exactly eight posts across four weeks and still showed that complete plan after reload.",
      "beforeImage": "assets/qa-live/chat/16-before-reported-issue.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/chat/16-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/16-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/16-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "17",
      "task": "AI-12989",
      "section": "Chatting with SaltBot",
      "title": "Generate and save the full reel script",
      "status": "fixed",
      "issue": "The Generate full script action from a calendar reel returned an empty result, then the chat stopped.",
      "steps": [
        "Generated a calendar with a reel.",
        "Opened that reel and used Generate full script.",
        "Required a complete script, then reloaded the chat and checked it remained."
      ],
      "result": "The full script generated, opened, and remained saved after reload.",
      "beforeImage": "assets/qa-live/chat/17-before-reported-issue.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/chat/17-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/17-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/17-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "18",
      "task": "AI-12990",
      "section": "Chatting with SaltBot",
      "title": "Package exactly four carousels without losing work",
      "status": "fixed",
      "issue": "SaltBot counted seven carousels when only four existed, hung for minutes, then refreshed and lost the work.",
      "steps": [
        "Requested exactly four complete five-slide carousel assets in one package.",
        "Opened every card and checked that each contained five complete slides.",
        "Hard-reloaded the chat, then reopened all four cards and checked the same slide totals again."
      ],
      "result": "SaltBot returned exactly four openable five-slide carousels, and the same four complete carousels remained after reload.",
      "beforeImage": "assets/qa-live/chat/18-before-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/chat/18-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/18-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/18-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "19",
      "task": "AI-12991",
      "section": "Chatting with SaltBot",
      "title": "Improve hooks and copy so they sound like Salt",
      "status": "fixed",
      "issue": "The hooks and copy sounded generic, predictable, and disconnected from the listing.",
      "steps": [
        "Supplied six approved facts and a plain written Salt voice rubric.",
        "Requested one hook-set result containing exactly five distinct hooks under 24 words.",
        "Opened the result, checked every hook against the rubric, hard-reloaded, and reopened the same saved set."
      ],
      "result": "One saved hook-set card contained exactly five distinct hooks. Every hook used an approved fact and stayed under 24 words; together they covered all six approved fact groups, avoided the banned generic phrases, and remained unchanged after reload.",
      "beforeImage": "assets/qa-live/chat/19-before-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/chat/19-after-live-result.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/chat/19-user-acceptance.mp4",
      "gif": "assets/qa-live/chat/19-user-acceptance.gif",
      "boundary": null,
      "cleanup": "The temporary test chat and its generated content were removed after capture."
    },
    {
      "id": "20",
      "task": "AI-12992",
      "section": "New features",
      "title": "Post Scheduler saves the full manual workflow",
      "status": "passed",
      "issue": "The report did not prove that a user could create a scheduled post, leave and return, copy the caption, mark it posted, and remove the test record without publishing to social media.",
      "steps": [
        "Created a future-dated post using the same controls a user sees.",
        "Reloaded the page and confirmed the post was still in the queue.",
        "Copied the caption and confirmed the copied words matched exactly.",
        "Marked the post as manually published, reloaded, and confirmed Published remained visible.",
        "Removed the temporary test record and reloaded to confirm cleanup."
      ],
      "result": "The full manual scheduling workflow passed. No social Publish action was clicked.",
      "beforeImage": "assets/qa-live/features/item-20-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-20-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-20.mp4",
      "gif": "assets/qa-live/features/gif/item-20.gif",
      "boundary": "This test intentionally stopped before social publishing because Tina’s feedback item was the manual scheduler workflow. Nothing was posted to Instagram.",
      "cleanup": "The temporary test post was deleted and remained absent after reload."
    },
    {
      "id": "21",
      "task": "AI-12993",
      "section": "New features",
      "title": "DM Automations is understandable and the safe draft flow works",
      "status": "fixed",
      "issue": "Tina said DM Automations felt overwhelming and it was not clear how a normal user should build and test a campaign.",
      "steps": [
        "Confirmed the main screen presents a three-step Trigger, Messages, Review path while advanced details stay collapsed.",
        "Started from the Home valuation template and changed it into a unique temporary test campaign.",
        "Saved the campaign as an off-by-default draft, reloaded, and confirmed it remained saved.",
        "Ran the built-in preview and confirmed the campaign produced test steps without sending a real message.",
        "Deleted the temporary test campaign and reloaded to confirm cleanup."
      ],
      "result": "The simplified campaign workflow passed from template through its built-in preview. The test draft stayed off and no Instagram message was sent.",
      "beforeImage": "assets/qa-live/features/item-21-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-21-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-21.mp4",
      "gif": "assets/qa-live/features/gif/item-21.gif",
      "boundary": "The built-in preview was used intentionally so the campaign could be tested without sending a real Instagram message.",
      "cleanup": "The temporary campaign and its preview activity were deleted and remained absent after reload."
    },
    {
      "id": "22",
      "task": "AI-12994",
      "section": "New features",
      "title": "DM Inbox shows Tina’s connected account and current messages",
      "status": "fixed",
      "issue": "Tina saw many DMs in Instagram but none in SaltBot and could not tell which inbox SaltBot was showing.",
      "steps": [
        "Signed in as Tina and confirmed @salt_cinema is Ready with its message connection active.",
        "Opened Tina’s DM Inbox and confirmed it clearly identifies salt_cinema as the connected account.",
        "Counted 16 current conversations, including messages triggered by a DM keyword or Instagram comment; the newest remained visible at the top.",
        "Clicked Refresh and confirmed all 16 conversations remained visible."
      ],
      "result": "Tina’s real Inbox was not empty, clearly identified @salt_cinema, and kept all 16 current conversations after Refresh.",
      "beforeImage": "assets/qa-live/features/item-22-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-22-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-22.mp4",
      "gif": "assets/qa-live/features/gif/item-22.gif",
      "boundary": "This run did not originate a new outside-account message because Instagram required a human verification step for the owned secondary test login. Tina’s receiving connection and messages already in her Inbox were still verified.",
      "cleanup": "Read-only test; no conversation, message, or account setting was changed."
    },
    {
      "id": "23",
      "task": "AI-12995",
      "section": "New features",
      "title": "Listing Launch produces a complete, readable launch bundle",
      "status": "fixed",
      "issue": "Tina said Listing Launch ran, but its copy did not make sense and the carousel was not good enough to use.",
      "steps": [
        "Entered a complete temporary test listing with price, bedrooms, bathrooms, size, and specific property highlights.",
        "Generated the launch bundle and waited for the real AI request to finish.",
        "Reviewed the Reel Script, Carousel, Caption Variants, Story Sequence, and DM Keyword sections one by one.",
        "Checked every section for missing or unreadable content.",
        "Deleted the generated bundle from Content Library and confirmed it was gone after reload."
      ],
      "result": "The real generation completed and returned all five promised deliverables in readable sections, with no missing or unreadable content.",
      "beforeImage": "assets/qa-live/features/item-23-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-23-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-23.mp4",
      "gif": "assets/qa-live/features/gif/item-23.gif",
      "boundary": "This acceptance test proves completeness, readability, and absence of broken output. Final taste and brand-voice preference still belongs to Tina, who supplied the original creative feedback.",
      "cleanup": "The temporary test listing bundle was deleted from Content Library and remained absent after reload."
    },
    {
      "id": "24",
      "task": "AI-12996",
      "section": "New features",
      "title": "The reported Instagram post now syncs to its Reel play count",
      "status": "fixed",
      "issue": "Tina showed an Instagram post with about 33,000 views while SaltBot reported 167, and older-post sync also returned wrong numbers.",
      "steps": [
        "Opened the exact saved @utahrealestatepaige post from Tina’s screenshot and recorded the incorrect 167-view state.",
        "Selected Sync Metrics from the post’s own menu and waited for Instagram to return the refreshed result.",
        "Reloaded the page, reopened the same post, and confirmed the completed values remained saved.",
        "Compared the visible result with the direct Instagram response: 31,723 views, 445 likes, and 29 comments matched."
      ],
      "result": "Passed on the exact reported post: Sync Metrics changed 167 views to 31,723 Reel plays, and 31,723 views, 445 likes, and 29 comments remained correct after reload.",
      "beforeImage": "assets/source/kix.1qb8okj2wkch.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-24-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-24.mp4",
      "gif": "assets/qa-live/features/gif/item-24.gif",
      "boundary": null,
      "cleanup": "The existing tracked post was preserved; no Instagram content was created or deleted."
    },
    {
      "id": "25",
      "task": "AI-12997",
      "section": "New features",
      "title": "Analyze Content still produces and saves a useful result",
      "status": "passed",
      "issue": "Tina said Analyze Content worked well, so this is a regression test to make sure later fixes did not break a feature she relies on.",
      "steps": [
        "Pasted a new real-estate caption into Analyze Content.",
        "Ran the real analysis and waited for the scored result.",
        "Saved the analysis, reloaded the page, reopened it from Saved Analyses, and confirmed the score remained available.",
        "Deleted the temporary test analysis and reloaded to confirm cleanup."
      ],
      "result": "Analyze Content passed end to end: it produced a scored breakdown, saved it, and reopened the saved result after a full reload.",
      "beforeImage": "assets/qa-live/features/item-25-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-25-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-25.mp4",
      "gif": "assets/qa-live/features/gif/item-25.gif",
      "boundary": null,
      "cleanup": "The temporary test analysis was deleted and remained absent after reload."
    },
    {
      "id": "26",
      "task": "AI-12998",
      "section": "New features",
      "title": "Zillow research completes once and opens the saved Market Intel result",
      "status": "fixed",
      "issue": "Tina said Zillow research took too long, showed two “something went wrong” errors, and only then opened Market Intel.",
      "steps": [
        "Pasted a real Zillow home-values link into Research Library and supplied a unique market label.",
        "Ran Analyze and save while timing the request and watching for a failure state.",
        "Confirmed exactly one success path, opened the saved report, and verified the full Market Intel report appeared.",
        "Reloaded Market Intel and confirmed the same saved report, market label, and result remained visible.",
        "Deleted the temporary test research report and reloaded Research Library to confirm cleanup."
      ],
      "result": "The Zillow research completed on the first attempt without the two-error loop, opened as a complete Market Intel report, and remained complete after a full reload.",
      "beforeImage": "assets/qa-live/features/item-26-reported-issue.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-26-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-26.mp4",
      "gif": "assets/qa-live/features/gif/item-26.gif",
      "boundary": "When Zillow does not allow SaltBot to read a page directly, this check accepts the clearly labeled conservative estimate only if it completes once and saves a usable report without an error loop.",
      "cleanup": "The temporary test market report was deleted and remained absent after reload."
    },
    {
      "id": "27",
      "task": "AI-12999",
      "section": "New features",
      "title": "In-progress Carousel Designer work survives tab changes, moving between pages, and reload",
      "status": "fixed",
      "issue": "Tina said her unfinished SaltBot work disappeared when she switched tabs to collect a link or more information.",
      "steps": [
        "Entered a unique unfinished headline, body, and brand handle in Carousel Designer.",
        "Opened another SaltBot page in a second browser tab, switched to it, and returned to the draft.",
        "Navigated to Brainstorm and back, then performed a full page reload.",
        "Confirmed all draft words remained after every transition.",
        "Restored the exact pre-test draft values and confirmed the restoration after reload."
      ],
      "result": "The unfinished carousel remained intact through a browser-tab switch, moving to another SaltBot page, and a full reload.",
      "beforeImage": "assets/qa-live/features/item-27-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-27-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-27.mp4",
      "gif": "assets/qa-live/features/gif/item-27.gif",
      "boundary": null,
      "cleanup": "The exact original draft values were restored and confirmed after reload."
    },
    {
      "id": "28",
      "task": "AI-13000",
      "section": "New features",
      "title": "All four Brainstorm categories generate and save results",
      "status": "fixed",
      "issue": "Tina said Trending Formats and Content Ideas failed constantly while Market Trends and Viral Hooks worked.",
      "steps": [
        "Used the same unique La Jolla market across Trending Formats, Market Trends, Content Ideas, and Viral Hooks.",
        "Ran each real research request separately and waited for a non-empty idea count.",
        "Confirmed each category auto-saved, then reloaded and confirmed the most recent saved result remained.",
        "Deleted every temporary saved research report and confirmed cleanup after reload."
      ],
      "result": "All four Brainstorm categories passed after a full reload. Trending Formats returned four ideas, Market Trends returned eight, Content Ideas returned three, and Viral Hooks returned four.",
      "beforeImage": "assets/source/kix.xs7esetreorg.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-28-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-28.mp4",
      "gif": "assets/qa-live/features/gif/item-28.gif",
      "boundary": null,
      "cleanup": "All four temporary Brainstorm reports were deleted and remained absent after reload."
    },
    {
      "id": "29A",
      "task": "AI-13002",
      "section": "New features",
      "title": "Instagram Audit completes without the page error",
      "status": "fixed",
      "issue": "Tina repeatedly saw an application error while an Instagram account audit was running.",
      "steps": [
        "Ran a real public-handle audit for @saltcinema.",
        "Waited through the live progress state and confirmed a complete Executive Summary, strengths, weaknesses, Bio Rewrite, and strategy appeared.",
        "Reloaded the page and confirmed the completed audit remained available.",
        "Verified the Bio Rewrite copy action when a rewritten bio was present.",
        "Deleted only the newly created audit asset and restored the original library count."
      ],
      "result": "The full audit completed, opened normally, and remained readable after reload without the previous application error.",
      "beforeImage": "assets/source/kix.9zzsg3gqs61h.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-29A-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-29A.mp4",
      "gif": "assets/qa-live/features/gif/item-29A.gif",
      "boundary": null,
      "cleanup": "The new test audit was deleted, and the original library remained unchanged."
    },
    {
      "id": "29B",
      "task": "AI-13003",
      "section": "New features",
      "title": "Competitor comparison accepts all three profile formats",
      "status": "fixed",
      "issue": "Tina said competitor comparison failed whether she entered a handle, an @handle, or a full Instagram profile link.",
      "steps": [
        "Opened Instagram Audit as Tina and confirmed the connected @salt_cinema account was in use.",
        "Ran a full comparison with the bare handle julianbradleytv.",
        "Repeated the full comparison with @julianbradleytv and with the complete Instagram profile link.",
        "Confirmed all three entries opened the same comparison using Tina’s connected account."
      ],
      "result": "All three reported entry formats passed and produced the same @salt_cinema versus @julianbradleytv comparison.",
      "beforeImage": "assets/source/kix.wvekd23oecxj.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-29B-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-29B.mp4",
      "gif": "assets/qa-live/features/gif/item-29B.gif",
      "boundary": null,
      "cleanup": "The three audit records created by this test were removed, and the two pre-existing audit records remained untouched."
    },
    {
      "id": "29C",
      "task": "AI-13001",
      "section": "New features",
      "title": "Connected Instagram audit matches Instagram’s live numbers",
      "status": "fixed",
      "issue": "Tina said some engagement numbers in Instagram Audit did not match Instagram.",
      "steps": [
        "Opened Tina’s Connected Instagram insights and compared the visible cards with a direct Instagram response.",
        "Confirmed the final visible values: 31,010 followers, 182,003 views, 83,135 reach, and 4,443 interactions.",
        "Ran a fresh connected-account audit and confirmed its 31,010 followers, 1,020 following, and 144 posts matched Instagram.",
        "Reviewed the generated audit text and found no contradictory numbers or totals that did not add up."
      ],
      "result": "Tina’s connected @salt_cinema account matched Instagram at 31,010 followers, 182,003 recent views, 83,135 accounts reached, and 4,443 interactions; the fresh audit also matched 1,020 following and 144 posts.",
      "beforeImage": "assets/source/kix.oqkzm9puuw4.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-29C-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-29C.mp4",
      "gif": "assets/qa-live/features/gif/item-29C.gif",
      "boundary": "Instagram totals can increase as new activity arrives. The proof records the exact numbers returned at the final July 16 check.",
      "cleanup": "The single audit record created by this test was removed; Tina’s connected account and existing content were not changed."
    },
    {
      "id": "30",
      "task": "AI-13004",
      "section": "New features",
      "title": "Carousel Designer renders, retains, and exports a linked image",
      "status": "fixed",
      "issue": "Tina liked that Carousel Designer retained her copy, but adding an image link repeatedly produced an error.",
      "steps": [
        "Pasted a real public PNG link into Image background and enabled image backgrounds.",
        "Confirmed the image appeared on a complete 1080×1350 slide with no visible error.",
        "Downloaded slide 1 and verified the downloaded image opened correctly.",
        "Reloaded and confirmed the linked image link remained in the draft.",
        "Restored the exact original draft values and confirmed restoration after reload."
      ],
      "result": "The linked image appeared correctly, the finished slide downloaded successfully, and the draft kept the same image after reload.",
      "beforeImage": "assets/source/kix.8k0kilxgla4z.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-30-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-30.mp4",
      "gif": "assets/qa-live/features/gif/item-30.gif",
      "boundary": null,
      "cleanup": "The exact original Carousel Designer draft was restored and confirmed after reload."
    },
    {
      "id": "31",
      "task": "AI-13005",
      "section": "New features",
      "title": "Listing Reel is kept out of this release",
      "status": "fixed",
      "issue": "Tina said Listing Reel was only a slideshow and should not be part of this release.",
      "steps": [
        "Entered the older Listing Reel page address while signed in.",
        "Confirmed SaltBot redirected to Dashboard instead of opening the deferred tool.",
        "Confirmed no Listing Reel link exists in the current sidebar navigation."
      ],
      "result": "Listing Reel is not exposed in this release. It is absent from navigation, and opening its older page address returns to the main SaltBot screen.",
      "beforeImage": "assets/qa-live/features/item-31-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-31-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-31.mp4",
      "gif": "assets/qa-live/features/gif/item-31.gif",
      "boundary": null,
      "cleanup": "Read-only page check; no data was created."
    },
    {
      "id": "32",
      "task": "AI-13006",
      "section": "New features",
      "title": "Transaction Concierge is kept out of this release",
      "status": "fixed",
      "issue": "Tina said Transaction Concierge should be deferred because sensitive transaction information should not be handled until the feature is rock solid.",
      "steps": [
        "Entered the older Transaction Concierge page address while signed in.",
        "Confirmed SaltBot redirected to Dashboard instead of opening the deferred tool.",
        "Confirmed no Transaction Concierge link exists in the current sidebar navigation."
      ],
      "result": "Transaction Concierge is not exposed in this release. It is absent from navigation, and opening its older page address returns to the main SaltBot screen.",
      "beforeImage": "assets/qa-live/features/item-32-before.png",
      "beforeLabel": "Issue or starting state",
      "afterImage": "assets/qa-live/features/item-32-after.png",
      "afterLabel": "Result after the user test",
      "video": "assets/qa-live/features/video/item-32.mp4",
      "gif": "assets/qa-live/features/gif/item-32.gif",
      "boundary": null,
      "cleanup": "Read-only page check; no data was created."
    },
    {
      "id": "33",
      "task": "AI-13007",
      "section": "New features",
      "title": "Self-Clone generation requires an approved, consented person photo",
      "status": "blocked",
      "issue": "Tina said Self Clone reached about 98% and then failed repeatedly instead of returning a saved image.",
      "steps": [
        "Opened AI Self-Clone with the dedicated test account and confirmed no previous result or consent existed.",
        "Entered a real generation instruction and pressed Generate.",
        "Confirmed the safety gate stopped before any request because a reference photo was missing.",
        "Verified the remaining checkbox requires the tester to affirm that the uploaded photo is their own likeness."
      ],
      "result": "SaltBot correctly stopped before generation because no person photo was supplied. Repeating the earlier 98%-then-fail sequence requires a photo whose owner has explicitly approved AI likeness generation.",
      "beforeImage": "assets/source/kix.ad5xafadivih.png",
      "beforeLabel": "Tina's original screenshot",
      "afterImage": "assets/qa-live/features/item-33-after.png",
      "afterLabel": "Current verified access gate",
      "video": "assets/qa-live/features/video/item-33.mp4",
      "gif": "assets/qa-live/features/gif/item-33.gif",
      "boundary": "Exact safety blocker: no approved person photo whose owner has consented to AI likeness generation. I did not falsely check “this photo is of me” for Tina, Sidney, a team member, or an unconsented image.",
      "cleanup": "No photo was uploaded, no consent was recorded, and no generation job or asset was created."
    }
  ]
};
